export const STARTER_TEMPLATES = [
  {
    id: "starter-default",
    name: "Plantilla predeterminada",
    category: "BASIC",
    subject: "Novedades y actualización importante",
    previewText: "Descubre todo lo nuevo que preparamos para ti",
    thumbnailUrl: "https://images.unsplash.com/photo-1579546929518-9e396f3cc809?w=600&auto=format&fit=crop&q=60",
    content: [
      {
        id: "blk-logo-1",
        type: "logo",
        label: "Logotipo",
        options: {
          imageUrl: "",
          alt: "Logo",
          align: "center",
          width: 140,
        },
      },
      {
        id: "blk-head-1",
        type: "heading",
        label: "Este es el titular.",
        options: {
          text: "Este es el titular.",
          level: 1,
          align: "center",
          color: "#111827",
          fontSize: 28,
        },
      },
      {
        id: "blk-img-1",
        type: "image",
        label: "Imagen Principal",
        options: {
          imageUrl: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&auto=format&fit=crop&q=80",
          alt: "Banner",
          align: "center",
        },
      },
      {
        id: "blk-txt-1",
        type: "text",
        label: "Texto descriptivo",
        options: {
          text: "Te invitamos a ser parte de esta experiencia única. Aquí encontrarás toda la información detallada para aprovechar al máximo este evento.",
          align: "center",
          color: "#4b5563",
          fontSize: 14,
          lineHeight: 1.6,
        },
      },
      {
        id: "blk-btn-1",
        type: "button",
        label: "Confirmar Asistencia",
        options: {
          text: "Confirmar Asistencia",
          url: "https://ejemplo.com",
          align: "center",
          bgColor: "#009245",
          textColor: "#ffffff",
          borderRadius: 8,
        },
      },
      {
        id: "blk-div-1",
        type: "divider",
        label: "Divisor",
        options: { color: "#e5e7eb", height: 1, marginY: 24 },
      },
      {
        id: "blk-soc-1",
        type: "social",
        label: "Redes Sociales",
        options: {
          align: "center",
          networks: [
            { name: "facebook", url: "https://facebook.com" },
            { name: "instagram", url: "https://instagram.com" },
            { name: "linkedin", url: "https://linkedin.com" },
            { name: "web", url: "https://ejemplo.com" },
          ],
        },
      },
    ],
  },
  {
    id: "starter-hubspot-confirm",
    name: "Confirmación de Correo (Estilo HubSpot)",
    category: "BASIC",
    subject: "Please confirm your email address",
    previewText: "Thanks for signing up to HubSpot. We're happy to have you.",
    thumbnailUrl: "https://images.unsplash.com/photo-1596526131083-e8c633c948d2?w=600&auto=format&fit=crop&q=60",
    content: [
      {
        id: "blk-hb-logo",
        type: "logo",
        label: "Cabecera HubSpot",
        options: {
          text: "HubSpot",
          align: "center",
          bgColor: "#FF7A59",
          textColor: "#ffffff",
          isBanner: true,
          paddingY: 16,
        },
      },
      {
        id: "blk-hb-img",
        type: "image",
        label: "Sobre de Confirmación",
        options: {
          imageUrl: "https://images.unsplash.com/photo-1596526131083-e8c633c948d2?w=600&auto=format&fit=crop&q=80",
          alt: "Confirm email",
          align: "center",
        },
      },
      {
        id: "blk-hb-head",
        type: "heading",
        label: "Título",
        options: {
          text: "Please confirm your email address",
          level: 1,
          align: "center",
          color: "#1e293b",
          fontSize: 26,
        },
      },
      {
        id: "blk-hb-txt",
        type: "text",
        label: "Mensaje",
        options: {
          text: "Thanks for signing up to HubSpot, {{ contact.FIRSTNAME | default: '' }}. We're happy to have you.\n\nPlease take a second to make sure we have your correct email address.",
          align: "center",
          color: "#475569",
          fontSize: 14,
          lineHeight: 1.6,
        },
      },
      {
        id: "blk-hb-btn",
        type: "button",
        label: "Botón Confirmación",
        options: {
          text: "Confirm your email address",
          url: "https://ejemplo.com/confirm",
          align: "center",
          bgColor: "#33475B",
          textColor: "#ffffff",
          borderRadius: 6,
        },
      },
      {
        id: "blk-hb-foot",
        type: "text",
        label: "Pie de Seguridad",
        options: {
          text: "Didn't sign up for HubSpot? <a href='#' style='color: #0284c7;'>Let us know.</a>",
          align: "center",
          color: "#94a3b8",
          fontSize: 12,
        },
      },
    ],
  },
  {
    id: "starter-workangel-approval",
    name: "Aprobación de Cuenta & App (Estilo WorkAngel)",
    category: "BASIC",
    subject: "Your WorkAngel account has been approved!",
    previewText: "You can now log in to the Luna network and download the mobile app.",
    thumbnailUrl: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=600&auto=format&fit=crop&q=60",
    content: [
      {
        id: "blk-wa-logo",
        type: "logo",
        label: "Insignia Circular",
        options: {
          text: "W",
          align: "center",
          bgColor: "#0ea5e9",
          textColor: "#ffffff",
          badgeShape: "circle",
          width: 50,
        },
      },
      {
        id: "blk-wa-head",
        type: "heading",
        label: "Saludo",
        options: {
          text: "Hi {{ contact.FIRSTNAME | default: 'Filippo' }},\nyour WorkAngel account has been approved!",
          align: "center",
          level: 1,
          color: "#1e293b",
          fontSize: 24,
        },
      },
      {
        id: "blk-wa-txt",
        type: "text",
        label: "Texto Acceso",
        options: {
          text: "Your WorkAngel account has been approved and you can now log in to the Luna network.\n\nYou can access WorkAngel online or on any device by going to <a href='http://luna.workangel.com' style='color: #0284c7;'>http://luna.workangel.com</a>",
          align: "center",
          color: "#475569",
          fontSize: 13,
          lineHeight: 1.6,
        },
      },
      {
        id: "blk-wa-btn",
        type: "button",
        label: "Botón Comenzar",
        options: {
          text: "Get started",
          url: "http://luna.workangel.com",
          align: "center",
          bgColor: "#0284c7",
          textColor: "#ffffff",
          borderRadius: 6,
        },
      },
      {
        id: "blk-wa-div1",
        type: "divider",
        label: "Divisor",
        options: { color: "#e2e8f0", height: 1, marginY: 20 },
      },
      {
        id: "blk-wa-apphead",
        type: "heading",
        label: "Titular App",
        options: {
          text: "Get the WorkAngel app!",
          level: 2,
          align: "center",
          color: "#0f172a",
          fontSize: 20,
        },
      },
      {
        id: "blk-wa-apptxt",
        type: "text",
        label: "Texto App",
        options: {
          text: "Get the most of WorkAngel by installing the mobile app.\nYou can log in by using your existing emails address and password.",
          align: "center",
          color: "#64748b",
          fontSize: 13,
          lineHeight: 1.5,
        },
      },
      {
        id: "blk-wa-appbtn",
        type: "button",
        label: "Badges de Tienda",
        options: {
          text: "Available on App Store & Google Play",
          url: "https://ejemplo.com/app",
          align: "center",
          bgColor: "#000000",
          textColor: "#ffffff",
          borderRadius: 8,
        },
      },
      {
        id: "blk-wa-soc",
        type: "social",
        label: "Redes Sociales",
        options: {
          align: "center",
          networks: [
            { name: "facebook", url: "https://facebook.com" },
            { name: "twitter", url: "https://twitter.com" },
            { name: "linkedin", url: "https://linkedin.com" },
          ],
        },
      },
    ],
  },
  {
    id: "starter-universe-welcome",
    name: "Bienvenida a Universe (Estilo Universe)",
    category: "BASIC",
    subject: "Welcome to Universe, Smiles Davis!",
    previewText: "We have everything you need to launch your event today.",
    thumbnailUrl: "https://images.unsplash.com/photo-1511578314322-379afb476865?w=600&auto=format&fit=crop&q=60",
    content: [
      {
        id: "blk-uv-img",
        type: "image",
        label: "Ilustración Saludo Mano",
        options: {
          imageUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=600&auto=format&fit=crop&q=80",
          alt: "Welcome to Universe",
          align: "center",
        },
      },
      {
        id: "blk-uv-head",
        type: "heading",
        label: "Titular Bienvenida",
        options: {
          text: "Welcome to Universe, {{ contact.FIRSTNAME | default: 'Smiles Davis' }}!",
          level: 1,
          align: "center",
          color: "#0f172a",
          fontSize: 26,
        },
      },
      {
        id: "blk-uv-txt",
        type: "text",
        label: "Texto Principal",
        options: {
          text: "We're glad to see you here! We have everything you need to launch your event today. <a href='#' style='color: #4f46e5;'>Learn more</a> on how you can set up your best event yet.",
          align: "center",
          color: "#475569",
          fontSize: 14,
          lineHeight: 1.6,
        },
      },
      {
        id: "blk-uv-btn",
        type: "button",
        label: "Botón Crear Evento",
        options: {
          text: "Create your event now",
          url: "https://ejemplo.com/create",
          align: "center",
          bgColor: "#4f46e5",
          textColor: "#ffffff",
          borderRadius: 8,
        },
      },
      {
        id: "blk-uv-subhead",
        type: "heading",
        label: "Subtítulo Asistir",
        options: {
          text: "Looking to attend an event?",
          level: 2,
          align: "center",
          color: "#1e293b",
          fontSize: 18,
        },
      },
      {
        id: "blk-uv-subtxt",
        type: "text",
        label: "Texto Descubrir",
        options: {
          text: "Use Universe to <a href='#' style='color: #4f46e5;'>discover events</a> happening near you.",
          align: "center",
          color: "#64748b",
          fontSize: 13,
        },
      },
      {
        id: "blk-uv-help",
        type: "text",
        label: "Caja de Ayuda",
        options: {
          text: "<strong>Have questions?</strong><br/>We are here to help, learn more about Universe <a href='#' style='color: #4f46e5;'>here</a> or <a href='#' style='color: #4f46e5;'>contact us</a>.",
          align: "center",
          color: "#64748b",
          fontSize: 12,
        },
      },
    ],
  },
  {
    id: "starter-hellothere-services",
    name: "Boletín de Servicios (.hello there)",
    category: "BASIC",
    subject: ".hello there - Potenciamos tus eventos al siguiente nivel",
    previewText: "Conoce todas las capacidades y ventajas de nuestro equipo.",
    thumbnailUrl: "https://images.unsplash.com/photo-1517976487507-5b3df1429945?w=600&auto=format&fit=crop&q=60",
    content: [
      {
        id: "blk-ht-head",
        type: "heading",
        label: "Cabecera Hero Azul",
        options: {
          text: ".hello there",
          subtitle: "Un equipo especializado y moderno para gestionar y optimizar tus convocatorias.",
          align: "center",
          level: 1,
          color: "#ffffff",
          bgColor: "#2563eb",
          paddingY: 28,
          fontSize: 32,
        },
      },
      {
        id: "blk-ht-img",
        type: "image",
        label: "Gráfico Origami",
        options: {
          imageUrl: "https://images.unsplash.com/photo-1517976487507-5b3df1429945?w=800&auto=format&fit=crop&q=80",
          alt: "Hero Header",
          align: "center",
        },
      },
      {
        id: "blk-ht-sec1",
        type: "heading",
        label: "Titular Capacidades",
        options: {
          text: "Esto es lo que podemos hacer:",
          level: 2,
          align: "left",
          color: "#0f172a",
          fontSize: 20,
        },
      },
      {
        id: "blk-ht-txt1",
        type: "text",
        label: "Lista de Puntos",
        options: {
          text: "• Registro online y validación de aforo con QR.<br/>• Emisión automatizada de certificados con verificación criptográfica.<br/>• Comunicación multicanal por correo electrónico y WhatsApp.<br/>• Reportes analíticos en tiempo real para organizadores.",
          align: "left",
          color: "#334155",
          fontSize: 13,
          lineHeight: 1.8,
        },
      },
      {
        id: "blk-ht-sec2",
        type: "heading",
        label: "Titular Eficiencia",
        options: {
          text: "Es fácil y efectivo trabajar juntos:",
          level: 2,
          align: "left",
          color: "#0f172a",
          fontSize: 18,
        },
      },
      {
        id: "blk-ht-txt2",
        type: "text",
        label: "Lista de Eficiencia",
        options: {
          text: "• 100% en la nube: Sin instalaciones complejas ni demoras.<br/>• Soporte integral durante la jornada del evento.<br/>• Cumplimiento garantizado y máxima puntualidad.",
          align: "left",
          color: "#475569",
          fontSize: 13,
          lineHeight: 1.8,
        },
      },
      {
        id: "blk-ht-btn",
        type: "button",
        label: "Botón Enviar Solicitud",
        options: {
          text: "Solicitar una demo ahora",
          url: "https://ejemplo.com/demo",
          align: "center",
          bgColor: "#2563eb",
          textColor: "#ffffff",
          borderRadius: 8,
        },
      },
    ],
  },
  {
    id: "starter-product",
    name: "Vender un producto o entrada",
    category: "PRODUCT",
    subject: "Equipamiento esencial para cada aventura",
    previewText: "Asegura tu pase exclusivo antes de que se agote",
    thumbnailUrl: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&auto=format&fit=crop&q=60",
    content: [
      {
        id: "blk-logo-p",
        type: "logo",
        label: "Logotipo",
        options: { imageUrl: "", alt: "Logo", align: "center", width: 130 },
      },
      {
        id: "blk-head-p",
        type: "heading",
        label: "Equipamiento esencial para cada aventura",
        options: {
          text: "Equipamiento esencial para cada aventura",
          level: 1,
          align: "center",
          color: "#0f172a",
          fontSize: 26,
        },
      },
      {
        id: "blk-txt-p1",
        type: "text",
        label: "Subtítulo",
        options: {
          text: "Tanto si buscas momentos de serenidad como si te gustan las excursiones intensas, descubre nuestros nuevos pases y beneficios.",
          align: "center",
          color: "#64748b",
          fontSize: 14,
        },
      },
      {
        id: "blk-prod-1",
        type: "product",
        label: "Pase General Early Bird",
        options: {
          title: "Entrada VIP - Acceso Total",
          price: "S/ 150.00",
          imageUrl: "https://images.unsplash.com/photo-1505373877841-8d25f7d46678?w=800&auto=format&fit=crop&q=80",
          description: "Incluye acceso a todas las conferencias magistrales, talleres prácticos y certificado con código QR verificado.",
          buttonText: "Comprar Entrada",
          buttonUrl: "https://ejemplo.com/tickets",
        },
      },
    ],
  },
  {
    id: "starter-story",
    name: "Contar una historia / Newsletter",
    category: "STORY",
    subject: "Un mensaje especial para ti",
    previewText: "Queremos compartir contigo los avances más recientes",
    thumbnailUrl: "https://images.unsplash.com/photo-1499750310107-5fef28a66643?w=600&auto=format&fit=crop&q=60",
    content: [
      {
        id: "blk-logo-s",
        type: "logo",
        label: "Logotipo",
        options: { imageUrl: "", alt: "Logo", align: "left", width: 120 },
      },
      {
        id: "blk-head-s",
        type: "heading",
        label: "Hola {{ contact.FIRSTNAME | default: 'amigo' }},",
        options: {
          text: "Hola {{ contact.FIRSTNAME | default: 'amigo' }},",
          level: 2,
          align: "left",
          color: "#1e293b",
          fontSize: 22,
        },
      },
      {
        id: "blk-txt-s1",
        type: "text",
        label: "Cuerpo del mensaje",
        options: {
          text: "¡Un nuevo año significa nuevas oportunidades! Tanto si te has marcado grandes objetivos como si solo quieres perfeccionar tus habilidades, estamos listos para acompañarte en cada paso.",
          align: "left",
          color: "#334155",
          fontSize: 14,
          lineHeight: 1.7,
        },
      },
      {
        id: "blk-img-s",
        type: "image",
        label: "Imagen historia",
        options: {
          imageUrl: "https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=800&auto=format&fit=crop&q=80",
          alt: "Equipo",
          align: "center",
        },
      },
      {
        id: "blk-btn-s",
        type: "button",
        label: "Leer el artículo completo",
        options: {
          text: "Leer el artículo completo",
          url: "https://ejemplo.com/blog",
          align: "center",
          bgColor: "#2563eb",
          textColor: "#ffffff",
          borderRadius: 6,
        },
      },
    ],
  },
]
