export const STARTER_TEMPLATES = [
  {
    id: "starter-default",
    name: "Plantilla predeterminada",
    category: "BASIC",
    subject: "Novedades y actualización importante",
    previewText: "Descubre todo lo nuevo que preparamos para ti",
    thumbnailUrl: "https://images.unsplash.com/photo-1579546929518-9e396f3cc809?w=600&auto=format&fit=crop&q=60",
    content: [
      {
        id: "blk-logo-1",
        type: "logo",
        label: "Logotipo",
        options: {
          imageUrl: "",
          alt: "Logo",
          align: "center",
          width: 140,
        },
      },
      {
        id: "blk-head-1",
        type: "heading",
        label: "Este es el titular.",
        options: {
          text: "Este es el titular.",
          level: 1,
          align: "center",
          color: "#111827",
          fontSize: 28,
        },
      },
      {
        id: "blk-img-1",
        type: "image",
        label: "Imagen Principal",
        options: {
          imageUrl: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&auto=format&fit=crop&q=80",
          alt: "Banner",
          align: "center",
        },
      },
      {
        id: "blk-txt-1",
        type: "text",
        label: "Texto descriptivo",
        options: {
          text: "Te invitamos a ser parte de esta experiencia única. Aquí encontrarás toda la información detallada para aprovechar al máximo este evento.",
          align: "center",
          color: "#4b5563",
          fontSize: 14,
          lineHeight: 1.6,
        },
      },
      {
        id: "blk-btn-1",
        type: "button",
        label: "Confirmar Asistencia",
        options: {
          text: "Confirmar Asistencia",
          url: "https://ejemplo.com",
          align: "center",
          bgColor: "#009245",
          textColor: "#ffffff",
          borderRadius: 8,
        },
      },
      {
        id: "blk-div-1",
        type: "divider",
        label: "Divisor",
        options: { color: "#e5e7eb", height: 1, marginY: 24 },
      },
      {
        id: "blk-soc-1",
        type: "social",
        label: "Redes Sociales",
        options: {
          align: "center",
          networks: [
            { name: "facebook", url: "https://facebook.com" },
            { name: "instagram", url: "https://instagram.com" },
            { name: "linkedin", url: "https://linkedin.com" },
            { name: "web", url: "https://ejemplo.com" },
          ],
        },
      },
    ],
  },
  {
    id: "starter-product",
    name: "Vender un producto o entrada",
    category: "PRODUCT",
    subject: "Equipamiento esencial para cada aventura",
    previewText: "Asegura tu pase exclusivo antes de que se agote",
    thumbnailUrl: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&auto=format&fit=crop&q=60",
    content: [
      {
        id: "blk-logo-p",
        type: "logo",
        label: "Logotipo",
        options: { imageUrl: "", alt: "Logo", align: "center", width: 130 },
      },
      {
        id: "blk-head-p",
        type: "heading",
        label: "Equipamiento esencial para cada aventura",
        options: {
          text: "Equipamiento esencial para cada aventura",
          level: 1,
          align: "center",
          color: "#0f172a",
          fontSize: 26,
        },
      },
      {
        id: "blk-txt-p1",
        type: "text",
        label: "Subtítulo",
        options: {
          text: "Tanto si buscas momentos de serenidad como si te gustan las excursiones intensas, descubre nuestros nuevos pases y beneficios.",
          align: "center",
          color: "#64748b",
          fontSize: 14,
        },
      },
      {
        id: "blk-prod-1",
        type: "product",
        label: "Pase General Early Bird",
        options: {
          title: "Entrada VIP - Acceso Total",
          price: "S/ 150.00",
          imageUrl: "https://images.unsplash.com/photo-1505373877841-8d25f7d46678?w=800&auto=format&fit=crop&q=80",
          description: "Incluye acceso a todas las conferencias magistrales, talleres prácticos y certificado con código QR verificado.",
          buttonText: "Comprar Entrada",
          buttonUrl: "https://ejemplo.com/tickets",
        },
      },
    ],
  },
  {
    id: "starter-story",
    name: "Contar una historia / Newsletter",
    category: "STORY",
    subject: "Un mensaje especial para ti",
    previewText: "Queremos compartir contigo los avances más recientes",
    thumbnailUrl: "https://images.unsplash.com/photo-1499750310107-5fef28a66643?w=600&auto=format&fit=crop&q=60",
    content: [
      {
        id: "blk-logo-s",
        type: "logo",
        label: "Logotipo",
        options: { imageUrl: "", alt: "Logo", align: "left", width: 120 },
      },
      {
        id: "blk-head-s",
        type: "heading",
        label: "Hola {{ contact.FIRSTNAME | default: 'amigo' }},",
        options: {
          text: "Hola {{ contact.FIRSTNAME | default: 'amigo' }},",
          level: 2,
          align: "left",
          color: "#1e293b",
          fontSize: 22,
        },
      },
      {
        id: "blk-txt-s1",
        type: "text",
        label: "Cuerpo del mensaje",
        options: {
          text: "¡Un nuevo año significa nuevas oportunidades! Tanto si te has marcado grandes objetivos como si solo quieres perfeccionar tus habilidades, estamos listos para acompañarte en cada paso.",
          align: "left",
          color: "#334155",
          fontSize: 14,
          lineHeight: 1.7,
        },
      },
      {
        id: "blk-img-s",
        type: "image",
        label: "Imagen historia",
        options: {
          imageUrl: "https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=800&auto=format&fit=crop&q=80",
          alt: "Equipo",
          align: "center",
        },
      },
      {
        id: "blk-btn-s",
        type: "button",
        label: "Leer el artículo completo",
        options: {
          text: "Leer el artículo completo",
          url: "https://ejemplo.com/blog",
          align: "center",
          bgColor: "#2563eb",
          textColor: "#ffffff",
          borderRadius: 6,
        },
      },
    ],
  },
]
