import { BadRequestException, Injectable, NotFoundException } from '@nestjs/common';
import { PrismaService } from '../../database/prisma.service.js';
import { MailService } from '../mail/mail.service.js';

@Injectable()
export class AutomationService {
  constructor(private readonly prisma: PrismaService, private readonly mail: MailService) {}
  list(organizationId:string) { return this.prisma.marketingAutomation.findMany({ where:{organizationId}, include:{steps:{orderBy:{position:'asc'}},event:{select:{id:true,eventName:true,startDate:true}},_count:{select:{steps:true}}}, orderBy:{updatedAt:'desc'} }); }
  async create(organizationId:string, data:any) { if (data.eventId) { const event=await this.prisma.mainEvent.findFirst({where:{id:data.eventId,organizationId}}); if(!event) throw new BadRequestException('El evento no pertenece a la institución'); } return this.prisma.marketingAutomation.create({data:{organizationId,eventId:data.eventId||null,name:data.name,status:data.status||'DRAFT',steps:{create:(data.steps||[]).map((s:any,i:number)=>({position:i+1,timing:s.timing,offsetHours:Number(s.offsetHours||0),templateId:s.templateId||null,subject:s.subject||null,htmlContent:s.htmlContent||null,conditions:s.conditions||null}))},include:{steps:true}}); }
  async update(id:string,data:any) { const current=await this.prisma.marketingAutomation.findUnique({where:{id}}); if(!current) throw new NotFoundException('Automatización no encontrada'); return this.prisma.$transaction(async tx=>{ if(Array.isArray(data.steps)){await tx.marketingAutomationStep.deleteMany({where:{automationId:id}});} return tx.marketingAutomation.update({where:{id},data:{name:data.name,status:data.status, eventId:data.eventId, ...(Array.isArray(data.steps)?{steps:{create:data.steps.map((s:any,i:number)=>({position:i+1,timing:s.timing,offsetHours:Number(s.offsetHours||0),templateId:s.templateId||null,subject:s.subject||null,htmlContent:s.htmlContent||null,conditions:s.conditions||null}))}}:{})},include:{steps:{orderBy:{position:'asc'}}}}); }); }
  async queue(id:string) { const automation=await this.prisma.marketingAutomation.findUnique({where:{id},include:{event:true,steps:{orderBy:{position:'asc'}},organization:{include:{marketingContacts:true}}}}); if(!automation) throw new NotFoundException('Automatización no encontrada'); if(!automation.event) throw new BadRequestException('La automatización requiere un evento'); const now=new Date(); let queued=0; for(const contact of automation.organization.marketingContacts.filter(c=>c.consentStatus==='SUBSCRIBED'&&c.emailFallback)){for(const step of automation.steps){const date=this.when(step,automation.event.startDate,now); if(!date) continue; await this.prisma.emailDelivery.upsert({where:{stepId_recipientEmail:{stepId:step.id,recipientEmail:contact.emailFallback!}},update:{scheduledAt:date,status:'QUEUED'},create:{organizationId:automation.organizationId,automationId:id,stepId:step.id,contactId:contact.id,recipientEmail:contact.emailFallback!,scheduledAt:date}});queued++;}} return {queued}; }
  private when(step:any,eventStart:Date,now:Date){let date:Date; if(step.timing==='IMMEDIATE') date=now; else if(step.timing==='BEFORE_EVENT') date=new Date(eventStart.getTime()-step.offsetHours*3600000); else if(step.timing==='AFTER_EVENT') date=new Date(eventStart.getTime()+step.offsetHours*3600000); else date=new Date(now.getTime()+step.offsetHours*3600000); return date<now&&step.timing!=='IMMEDIATE'?null:date; }
  async dispatchDue(limit=100){const jobs=await this.prisma.emailDelivery.findMany({where:{status:'QUEUED',scheduledAt:{lte:new Date()}},take:limit,orderBy:{scheduledAt:'asc'}}); let sent=0,failed=0; for(const job of jobs){const step=await this.prisma.marketingAutomationStep.findUnique({where:{id:job.stepId}}); if(!step) continue; const result=await this.mail.send({to:job.recipientEmail,subject:step.subject||'Información importante',html:step.htmlContent||'<p>Gracias por registrarte.</p>'}); await this.prisma.emailDelivery.update({where:{id:job.id},data:result.sent?{status:'SENT',sentAt:new Date(),providerMessageId:result.messageId}:{status:'FAILED',error:result.reason}}); result.sent?sent++:failed++;} return {processed:jobs.length,sent,failed};}
  async analytics(organizationId:string){const group=await this.prisma.emailDelivery.groupBy({by:['status'],where:{organizationId},_count:{_all:true}}); return Object.fromEntries(group.map(x=>[x.status,x._count._all]));}
}
