import { useEffect, useState } from "react"
import { useNavigate, useParams } from "react-router-dom"
import { Plus, Trash2 } from "lucide-react"
import { api } from "@/api/client"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { PageHeader } from "@/components/page-header"
const types = ["text", "email", "tel", "textarea", "date", "select", "radio", "checkbox"]
export function EventFormBuilderPage() { const { id, formId } = useParams<{id:string;formId:string}>(); const navigate=useNavigate(); const [form,setForm]=useState<any>(); const [fields,setFields]=useState<any[]>([]); useEffect(()=>{if(id) api.registrationForms.list(id).then((list)=>{const item=list.find((x)=>x.id===formId);setForm(item);setFields(item?.fields||[])})},[id,formId]); const save=()=>api.registrationForms.update(formId!,{fields}).then(()=>alert("Diseño guardado")); if(!form)return <div className="p-8">Cargando…</div>; return <div className="mx-auto max-w-5xl space-y-6"><PageHeader title={`Diseñar: ${form.title}`} description="Configura y ordena los campos." actionButton={<div className="flex gap-2"><Button variant="outline" onClick={()=>navigate(`/dashboard/events/${id}/forms`)}>Volver</Button><Button onClick={save}>Guardar diseño</Button></div>}/><div className="space-y-3">{fields.map((field,index)=><div key={`${field.key}-${index}`} className="rounded-xl border bg-card p-4"><div className="grid gap-2 md:grid-cols-[1fr_120px_auto]"><Input value={field.label} onChange={(e)=>setFields((items)=>items.map((x,i)=>i===index?{...x,label:e.target.value}:x))}/><select className="h-9 rounded-md border bg-background px-2" value={field.type} onChange={(e)=>setFields((items)=>items.map((x,i)=>i===index?{...x,type:e.target.value}:x))}>{types.map((type)=><option key={type}>{type}</option>)}</select><Button size="icon" variant="ghost" onClick={()=>setFields((items)=>items.filter((_,i)=>i!==index))}><Trash2 className="size-4"/></Button></div></div>)}<Button variant="outline" onClick={()=>setFields((items)=>[...items,{key:`campo_${Date.now()}`,label:"Nuevo campo",type:"text",required:false}])}><Plus className="mr-1 size-3"/>Agregar campo</Button></div></div> }
