import { BadRequestException, Injectable, NotFoundException } from '@nestjs/common';
import { Prisma } from '@prisma/client';
import { PrismaService } from '../../database/prisma.service.js';

@Injectable()
export class RegistrationFormsService {
  constructor(private readonly prisma: PrismaService) {}
  list(eventId: string) { return this.prisma.registrationForm.findMany({ where: { mainEventId: eventId }, include: { fields: { orderBy: { position: 'asc' } }, _count: { select: { submissions: true } } }, orderBy: { createdAt: 'desc' } }); }
  async create(eventId: string, data: any) { if (data.editionId) { const edition = await this.prisma.edition.findFirst({ where: { id: data.editionId, mainEventId: eventId } }); if (!edition) throw new BadRequestException('La edición seleccionada no pertenece al evento'); } return this.prisma.registrationForm.create({ data: { mainEventId: eventId, title: data.title, description: data.description || null, slug: data.slug, editionId: data.editionId || null, status: data.status || 'DRAFT', opensAt: data.opensAt ? new Date(data.opensAt) : null, closesAt: data.closesAt ? new Date(data.closesAt) : null, maxSubmissions: data.maxSubmissions || null, approvalMode: data.approvalMode || 'MANUAL', allowEditionSelection: !!data.allowEditionSelection, defaultEditionId: data.defaultEditionId || null, fields: { create: (data.fields || []).map((field: any, position: number) => ({ key: field.key, label: field.label, type: field.type, required: !!field.required, options: field.options || null, validation: field.validation || null, position })) } }, include: { fields: true } }); }
  async update(id: string, data: any) { const clean: any = { ...data }; const fields = clean.fields; delete clean.fields; if (clean.opensAt) clean.opensAt = new Date(clean.opensAt); if (clean.closesAt) clean.closesAt = new Date(clean.closesAt); return this.prisma.$transaction(async (tx) => { if (Array.isArray(fields)) { await tx.registrationFormField.deleteMany({ where: { formId: id } }); clean.fields = { create: fields.map((field: any, position: number) => ({ key: field.key, label: field.label, type: field.type, required: !!field.required, options: field.options || null, validation: field.validation || null, position })) }; } return tx.registrationForm.update({ where: { id }, data: clean, include: { fields: { orderBy: { position: 'asc' } } } }); }); }
  async remove(id: string) { const uses = await this.prisma.registrationSubmission.count({ where: { formId: id } }); if (uses) throw new BadRequestException('No se puede eliminar un formulario con envíos; archívalo en su lugar.'); return this.prisma.registrationForm.delete({ where: { id } }); }
  async publicForm(slug: string) { const form = await this.prisma.registrationForm.findUnique({ where: { slug }, include: { fields: { orderBy: { position: 'asc' } }, mainEvent: { select: { eventName: true } }, edition: { select: { name: true } } } }); if (!form) throw new NotFoundException('Formulario no encontrado'); if (form.status !== 'PUBLISHED') throw new BadRequestException('Este formulario no está disponible'); const now = new Date(); if ((form.opensAt && now < form.opensAt) || (form.closesAt && now > form.closesAt)) throw new BadRequestException('Este formulario no está disponible en este momento'); return form; }
  async submit(slug: string, answers: Record<string, unknown>, editionId?: string) { const form = await this.publicForm(slug); const count = await this.prisma.registrationSubmission.count({ where: { formId: form.id } }); if (form.maxSubmissions && count >= form.maxSubmissions) throw new BadRequestException('Se alcanzó el límite de registros'); for (const field of form.fields) if (field.required && (answers[field.key] === undefined || answers[field.key] === '')) throw new BadRequestException(`El campo ${field.label} es obligatorio`); const email = typeof answers.email === 'string' ? answers.email : null; return this.prisma.registrationSubmission.create({ data: { formId: form.id, editionId: editionId || form.editionId || form.defaultEditionId || null, answers: answers as Prisma.InputJsonValue, email, status: form.approvalMode === 'AUTOMATIC' ? 'APPROVED' : 'PENDING' } }); }
}
