import { useEffect, useRef, useState } from "react"
import { Film, GripVertical, ImagePlus, Star, Upload, X } from "lucide-react"
import { toast } from "sonner"
import { api } from "@/api/client"
import { Button } from "@/components/ui/button"
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog"
type OwnerType = "ORGANIZATION" | "EVENT" | "EDITION" | "PROFILE"; type Purpose = "COVER" | "LOGO" | "GALLERY" | "DOCUMENT" | "OTHER"
export type MediaItem = { id: string; mediaId: string; url: string; mimeType: string; orientation?: string; position: number; isFeatured: boolean }
type Pending = { id: string; file: File; preview: string; orientation: "LANDSCAPE" | "PORTRAIT" | "SQUARE" | "VIDEO" | "OTHER" }
type Props = { open: boolean; onOpenChange: (open: boolean) => void; organizationId?: string; ownerType: OwnerType; ownerId: string; purpose?: Purpose; multiple?: boolean; maxItems?: number; title?: string; onChange?: (items: MediaItem[]) => void }
async function getOrientation(file: File): Promise<Pending["orientation"]> { if (file.type.startsWith("video/")) return "VIDEO"; if (!file.type.startsWith("image/")) return "OTHER"; const src = URL.createObjectURL(file); try { const image = new Image(); await new Promise<void>((ok, bad) => { image.onload = () => ok(); image.onerror = bad; image.src = src }); return image.width === image.height ? "SQUARE" : image.width > image.height ? "LANDSCAPE" : "PORTRAIT" } finally { URL.revokeObjectURL(src) } }
export function MediaLibraryDialog({ open, onOpenChange, organizationId, ownerType, ownerId, purpose = "GALLERY", multiple = false, maxItems = multiple ? 10 : 1, title = "Multimedia", onChange }: Props) {
  const [items, setItems] = useState<MediaItem[]>([]); const [pending, setPending] = useState<Pending[]>([]); const [library, setLibrary] = useState<any[]>([]); const [dragging, setDragging] = useState(false); const [busy, setBusy] = useState(false); const fileRef = useRef<HTMLInputElement>(null); const count = items.length + pending.length
  const refresh = async () => { if (!ownerId) return; const [links, assets] = await Promise.all([api.media.list(ownerType, ownerId), organizationId ? api.media.library(organizationId) : Promise.resolve([])]); const next = links.map((link: any) => ({ id: link.id, mediaId: link.mediaId, url: link.media.url, mimeType: link.media.mimeType, orientation: link.media.orientation, position: link.position, isFeatured: link.isFeatured })); setItems(next); onChange?.(next); setLibrary(assets) }
  useEffect(() => { if (open) void refresh().catch((error) => toast.error(error.message || "No se pudo cargar la biblioteca.")) }, [open, ownerId, organizationId])
  useEffect(() => () => pending.forEach((item) => URL.revokeObjectURL(item.preview)), [pending])
  const queue = async (files: FileList | File[]) => { const filesOk = Array.from(files).filter((file) => file.type.startsWith("image/") || file.type.startsWith("video/") || file.type === "application/pdf").slice(0, Math.max(0, maxItems - count)); if (!filesOk.length) return toast.error(`Puedes agregar un máximo de ${maxItems} archivo${maxItems === 1 ? "" : "s"}.`); const next = await Promise.all(filesOk.map(async (file) => ({ id: crypto.randomUUID(), file, preview: URL.createObjectURL(file), orientation: await getOrientation(file) }))); if (!multiple) { pending.forEach((item) => URL.revokeObjectURL(item.preview)); setPending(next.slice(0, 1)) } else setPending((current) => [...current, ...next]) }
  const removePending = (id: string) => setPending((current) => { const item = current.find((candidate) => candidate.id === id); if (item) URL.revokeObjectURL(item.preview); return current.filter((candidate) => candidate.id !== id) })
  const submit = async () => { if (!pending.length) return; setBusy(true); try { if (!multiple && items[0]) await api.media.unlink(items[0].id); for (const item of pending) await api.media.upload(item.file, { ownerType, ownerId, organizationId, purpose, position: items.length, orientation: item.orientation }); pending.forEach((item) => URL.revokeObjectURL(item.preview)); setPending([]); await refresh(); toast.success("Archivos subidos correctamente") } catch (error: any) { toast.error(error.message || "No se pudieron subir los archivos.") } finally { setBusy(false) } }
  const remove = async (item: MediaItem) => { try { await api.media.unlink(item.id); await refresh(); toast.success("Recurso retirado") } catch (error: any) { toast.error(error.message || "No se pudo retirar el recurso.") } }
  const selectLibrary = async (asset: any) => { if (count >= maxItems) return toast.error(`Máximo ${maxItems} archivos.`); try { await api.media.attach(asset.id, { ownerType, ownerId, purpose, position: items.length }); await refresh() } catch (error: any) { toast.error(error.message || "No se pudo usar ese archivo.") } }
  const feature = async (item: MediaItem) => { const next = items.map((candidate) => ({ ...candidate, isFeatured: candidate.id === item.id })); setItems(next); await api.media.reorder(ownerType, ownerId, next.map((candidate, position) => ({ id: candidate.id, position, isFeatured: candidate.isFeatured }))) }
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-h-[88vh] max-w-3xl overflow-y-auto rounded-lg p-5 shadow-none"><DialogHeader><DialogTitle className="font-medium">{title}</DialogTitle><DialogDescription>Prepara los archivos y confirma la carga cuando estén listos.</DialogDescription></DialogHeader><input ref={fileRef} type="file" multiple={multiple} accept="image/*,video/*,application/pdf" className="hidden" onChange={(event) => { if (event.target.files) void queue(event.target.files); event.target.value = "" }} />
    <section className="space-y-2"><p className="text-sm text-muted-foreground"><span className="font-medium text-foreground">Archivos · {count}/{maxItems}</span> · Puedes agregar un máximo de {maxItems}.</p><div className="flex flex-wrap gap-2">{items.map((item) => <Tile key={item.id} src={item.url} mime={item.mimeType} onRemove={() => void remove(item)} onFeature={ownerType === "EVENT" ? () => void feature(item) : undefined} featured={item.isFeatured} />)}{pending.map((item) => <Tile key={item.id} src={item.preview} mime={item.file.type} pending onRemove={() => removePending(item.id)} />)}{count < maxItems && <button type="button" onClick={() => fileRef.current?.click()} onDragOver={(event) => { event.preventDefault(); setDragging(true) }} onDragLeave={() => setDragging(false)} onDrop={(event) => { event.preventDefault(); setDragging(false); void queue(event.dataTransfer.files) }} className={`flex h-32 w-32 flex-col items-center justify-center gap-2 rounded-md border border-dashed text-sm text-muted-foreground transition-colors ${dragging ? "border-primary bg-muted" : "border-border bg-muted/40 hover:bg-muted"}`}><ImagePlus className="size-5" /><span>Agregar archivo</span></button>}</div></section>
    <div className="flex flex-wrap items-center justify-between gap-3 border-t border-border pt-4"><Button type="button" variant="outline" className="shadow-none" onClick={() => fileRef.current?.click()}><Upload /> Añadir archivos</Button><Button type="button" className="shadow-none" disabled={!pending.length || busy} onClick={() => void submit()}>{busy ? "Subiendo…" : `Subir archivos${pending.length ? ` (${pending.length})` : ""}`}</Button></div>
    {organizationId && <section className="space-y-2 border-t border-border pt-4"><p className="text-sm font-medium">Biblioteca de la organización</p><div className="grid grid-cols-4 gap-2 sm:grid-cols-6">{library.map((asset) => <button type="button" key={asset.id} onClick={() => void selectLibrary(asset)} className="overflow-hidden rounded-md border border-border bg-muted/30 text-left hover:bg-muted">{asset.mimeType.startsWith("video/") ? <div className="flex aspect-square items-center justify-center"><Film className="size-5" /></div> : <img src={asset.url} alt={asset.filename} className="aspect-square w-full object-cover" />}<span className="block truncate p-1 text-[10px]">{asset.filename}</span></button>)}</div></section>}
  </DialogContent></Dialog>
}
function Tile({ src, mime, pending = false, featured = false, onRemove, onFeature }: { src: string; mime: string; pending?: boolean; featured?: boolean; onRemove: () => void; onFeature?: () => void }) { return <div className="group relative h-32 w-32 overflow-hidden rounded-md border border-border bg-muted/30">{mime.startsWith("video/") ? <video src={src} className="size-full object-cover" muted /> : <img src={src} alt="Archivo multimedia" className="size-full object-cover" />}<div className="absolute inset-x-0 bottom-0 flex items-center justify-between bg-background/85 p-1 text-[10px] text-muted-foreground">{pending ? <span>Pendiente</span> : <GripVertical className="size-3" />}<div className="flex">{onFeature && <button type="button" title="Destacar en el hero" onClick={onFeature} className={featured ? "text-primary" : ""}><Star className="size-3.5" /></button>}<button type="button" title="Quitar" onClick={onRemove}><X className="ml-1 size-3.5" /></button></div></div></div> }
